baseURL = 'https://nickdesaulniers.github.io/'
languageCode = 'en-us'
title = 'Nick Desaulniers'
theme="Hugo-Octopress"
disqusShortname="wangstabill"

[permalinks]
# Configures post URLs
post="/blog/:year/:month/:day/:title/"

[params]
  subtitle="The enemy's gate is down"
  rss=true
  searchEngineURL="https://www.google.com/search"
  googleAnalytics="UA-36993986-1"

[[menu.main]]
  Name = "About"
  URL = "/about/"
  weight = -10
[[menu.main]]
  Name = "Archives"
  URL = "/"
  weight = -10
[[menu.main]]
  Name = "Blog"
  URL = "/"
  weight = -10
[[menu.main]]
  Name = "Publications"
  URL = "/publications/"
  weight = -10
[[menu.main]]
  Name = "Talks"
  URL = "/talks/"
  weight = -10
